<?php

namespace Database\Seeders;

use App\Models\NavigationMenu;
use Illuminate\Database\Seeder;

class NavigationMenuSeeder extends Seeder
{
    public function run(): void
    {
        NavigationMenu::where('menu_key', 'donasi_pendidikan')->delete();

        $menus = [
            [
                'menu_key' => 'home',
                'label' => 'Beranda',
                'route_name' => null,
                'url' => '/',
                'parent_key' => null,
                'sort_order' => 1,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'profile',
                'label' => 'Profil',
                'route_name' => 'public.profile',
                'url' => null,
                'parent_key' => null,
                'sort_order' => 2,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'program',
                'label' => 'Program',
                'route_name' => null,
                'url' => null,
                'parent_key' => null,
                'sort_order' => 4,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'program_pendidikan',
                'label' => 'Program Pendidikan',
                'route_name' => 'public.program',
                'url' => null,
                'parent_key' => 'program',
                'sort_order' => 1,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'struktur_organisasi',
                'label' => 'Struktur Organisasi',
                'route_name' => 'public.struktur-organisasi',
                'url' => '/struktur-organisasi',
                'parent_key' => null,
                'sort_order' => 3,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'kalender_pendidikan',
                'label' => 'Kalender',
                'route_name' => 'public.academic-calendar',
                'url' => null,
                'parent_key' => null,
                'sort_order' => 5,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'jadwal_pelajaran',
                'label' => 'Jadwal',
                'route_name' => 'public.lesson-schedule',
                'url' => null,
                'parent_key' => null,
                'sort_order' => 6,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'boarding',
                'label' => 'Boarding',
                'route_name' => 'public.boarding',
                'url' => null,
                'parent_key' => 'program',
                'sort_order' => 2,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'gallery',
                'label' => 'Galeri',
                'route_name' => 'public.gallery',
                'url' => null,
                'parent_key' => null,
                'sort_order' => 8,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'figures',
                'label' => 'Tokoh',
                'route_name' => 'public.figures',
                'url' => null,
                'parent_key' => null,
                'sort_order' => 9,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'teachers',
                'label' => 'Guru',
                'route_name' => 'public.teachers',
                'url' => null,
                'parent_key' => null,
                'sort_order' => 10,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'ppdb',
                'label' => 'SPMB',
                'route_name' => 'ppdb.info',
                'url' => null,
                'parent_key' => null,
                'sort_order' => 11,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'ppdb_info',
                'label' => 'Informasi SPMB',
                'route_name' => 'ppdb.info',
                'url' => null,
                'parent_key' => 'ppdb',
                'sort_order' => 1,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'ppdb_register',
                'label' => 'Daftar SPMB',
                'route_name' => 'ppdb.create',
                'url' => null,
                'parent_key' => 'ppdb',
                'sort_order' => 2,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'ppdb_status',
                'label' => 'Cek Status',
                'route_name' => 'ppdb.status.form',
                'url' => null,
                'parent_key' => 'ppdb',
                'sort_order' => 3,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'dukung_kami',
                'label' => 'Dukung Kami',
                'route_name' => null,
                'url' => null,
                'parent_key' => null,
                'sort_order' => 12,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'dukung_pendidikan',
                'label' => 'Dukung Pendidikan',
                'route_name' => 'donasi-pendidikan',
                'url' => '/donasi-pendidikan',
                'parent_key' => 'dukung_kami',
                'sort_order' => 1,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'infaq_uang',
                'label' => 'Infaq Uang',
                'route_name' => 'public.infaq-money',
                'url' => '/infaq-uang',
                'parent_key' => 'dukung_kami',
                'sort_order' => 2,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'infaq_barang',
                'label' => 'Infaq Barang',
                'route_name' => 'public.infaq-goods',
                'url' => '/infaq-barang',
                'parent_key' => 'dukung_kami',
                'sort_order' => 3,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'wakaf_uang',
                'label' => 'Wakaf Uang',
                'route_name' => 'wakaf-uang.index',
                'url' => '/wakaf-uang',
                'parent_key' => 'dukung_kami',
                'sort_order' => 4,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'orang_tua_asuh',
                'label' => 'Orang Tua Asuh',
                'route_name' => 'orang-tua-asuh',
                'url' => '/orang-tua-asuh',
                'parent_key' => 'dukung_kami',
                'sort_order' => 5,
                'location' => 'public_header',
                'is_active' => true,
            ],
            [
                'menu_key' => 'contact',
                'label' => 'Kontak',
                'route_name' => null,
                'url' => '/#kontak',
                'parent_key' => null,
                'sort_order' => 13,
                'location' => 'public_header',
                'is_active' => true,
            ],
        ];

        foreach ($menus as $menu) {
            NavigationMenu::updateOrCreate(
                ['menu_key' => $menu['menu_key']],
                $menu
            );
        }
    }
}
