<?php

return [
    'dashboard' => [
        'key' => 'dashboard',
        'label' => 'Dashboard',
        'route' => 'dashboard',
        'route_active' => 'dashboard',
        'icon' => 'home',
        'roles' => [],
    ],

    'sections' => [
        [
            'label' => 'SPMB',
            'items' => [
                [
                    'key' => 'ppdb.dashboard',
                    'label' => 'Dashboard SPMB',
                    'route' => 'admin.ppdb.dashboard',
                    'route_active' => 'admin.ppdb.dashboard',
                    'icon' => 'chart-bar',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah'],
                    'permission' => 'ppdb.dashboard.view',
                ],
                [
                    'key' => 'ppdb.applications',
                    'label' => 'Data Pendaftaran',
                    'route' => 'admin.ppdb.applications.index',
                    'route_active' => 'admin.ppdb.applications.*',
                    'icon' => 'document',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah'],
                    'permission' => 'ppdb.applications.view',
                ],
                [
                    'key' => 'ppdb.settings',
                    'label' => 'Pengaturan SPMB',
                    'route' => 'admin.ppdb.settings.edit',
                    'route_active' => 'admin.ppdb.settings.*',
                    'icon' => 'gear',
                    'roles' => ['superadmin', 'admin'],
                    'permission' => 'ppdb.settings.manage',
                ],
            ],
        ],
        [
            'label' => 'KEUANGAN',
            'items' => [
                [
                    'key' => 'finance.dashboard',
                    'label' => 'Dashboard Keuangan',
                    'route' => 'admin.finance.dashboard',
                    'route_active' => 'admin.finance.dashboard',
                    'icon' => 'pie-chart',
                    'roles' => ['superadmin', 'admin', 'staf_keuangan', 'kepala_sekolah'],
                    'permission' => 'finance.dashboard.view',
                ],
                [
                    'key' => 'finance.report',
                    'label' => 'Laporan',
                    'route' => 'admin.finance.report',
                    'route_active' => 'admin.finance.report',
                    'icon' => 'clipboard',
                    'indent' => true,
                    'roles' => ['superadmin', 'admin', 'staf_keuangan', 'kepala_sekolah'],
                    'permission' => 'finance.report.view',
                ],
                [
                    'key' => 'finance.incomes',
                    'label' => 'Pemasukan',
                    'route' => 'admin.finance.incomes.index',
                    'route_active' => 'admin.finance.incomes.*',
                    'icon' => 'arrow-down',
                    'indent' => true,
                    'roles' => ['superadmin', 'admin', 'staf_keuangan'],
                    'permission' => 'finance.transactions.manage',
                ],
                [
                    'key' => 'finance.expenses',
                    'label' => 'Pengeluaran',
                    'route' => 'admin.finance.expenses.index',
                    'route_active' => 'admin.finance.expenses.*',
                    'icon' => 'arrow-up',
                    'indent' => true,
                    'roles' => ['superadmin', 'admin', 'staf_keuangan'],
                    'permission' => 'finance.transactions.manage',
                ],
            ],
        ],
        [
            'label' => 'SURAT MENYURAT',
            'items' => [
                [
                    'key' => 'letters.types',
                    'label' => 'Jenis Surat',
                    'route' => 'admin.letters.types.index',
                    'route_active' => 'admin.letters.types.*',
                    'icon' => 'tag',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'letters.types.manage',
                ],
                [
                    'key' => 'letters.signers',
                    'label' => 'Penandatangan',
                    'route' => 'admin.letters.signers.index',
                    'route_active' => 'admin.letters.signers.*',
                    'icon' => 'pen',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'letters.signers.manage',
                ],
                [
                    'key' => 'letters.settings',
                    'label' => 'Pengaturan Surat',
                    'route' => 'admin.letters.settings.edit',
                    'route_active' => 'admin.letters.settings.*',
                    'icon' => 'gear',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'letters.settings.manage',
                ],
                [
                    'key' => 'letters.outgoings',
                    'label' => 'Surat Keluar',
                    'route' => 'admin.letters.outgoings.index',
                    'route_active' => 'admin.letters.outgoings.*',
                    'icon' => 'send',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha', 'kepala_sekolah'],
                    'permission' => 'letters.outgoings.view',
                ],
                [
                    'key' => 'letters.incomings',
                    'label' => 'Surat Masuk',
                    'route' => 'admin.letters.incomings.index',
                    'route_active' => 'admin.letters.incomings.*',
                    'icon' => 'inbox',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha', 'kepala_sekolah'],
                    'permission' => 'letters.incomings.view',
                ],
                [
                    'key' => 'letters.templates',
                    'label' => 'Template Surat',
                    'route' => 'admin.letters.templates.index',
                    'route_active' => 'admin.letters.templates.*',
                    'icon' => 'document',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'letters.templates.manage',
                ],
            ],
        ],
        [
            'label' => 'DONASI',
            'items' => [
                [
                    'key' => 'donation.receipt',
                    'label' => 'Bukti Penerimaan Donasi',
                    'route' => 'admin.donasi-transactions.create-receipt',
                    'route_active' => 'admin.donasi-transactions.create-receipt',
                    'icon' => 'plus',
                    'roles' => ['superadmin', 'admin', 'staf_keuangan'],
                    'permission' => 'donation.transactions.manage',
                ],
                [
                    'key' => 'donation.infaq-wa',
                    'label' => 'Data WA Infaq Barang',
                    'route' => 'admin.infaq-barang-wa.index',
                    'route_active' => 'admin.infaq-barang-wa.*',
                    'icon' => 'chat',
                    'roles' => ['superadmin', 'admin', 'staf_keuangan'],
                    'permission' => 'donation.infaq.manage',
                ],
                [
                    'key' => 'donation.transactions',
                    'label' => 'Donasi Masuk',
                    'route' => 'admin.donasi-transactions.index',
                    'route_active' => 'admin.donasi-transactions.index',
                    'icon' => 'checkmark',
                    'roles' => ['superadmin', 'admin', 'staf_keuangan', 'kepala_sekolah'],
                    'permission' => 'donation.transactions.view',
                ],
                [
                    'key' => 'donation.outflows',
                    'label' => 'Donasi Keluar',
                    'route' => 'admin.donation-outflows.index',
                    'route_active' => 'admin.donation-outflows.*',
                    'icon' => 'arrow-up',
                    'roles' => ['superadmin', 'admin', 'staf_keuangan'],
                    'permission' => 'donation.outflows.view',
                ],
                [
                    'key' => 'donation.education',
                    'label' => 'Donasi Pendidikan',
                    'route' => 'admin.website.donasi-pendidikan.edit',
                    'route_active' => 'admin.website.donasi-pendidikan.*',
                    'icon' => 'hands',
                    'roles' => ['superadmin', 'admin', 'staf_keuangan'],
                    'permission' => 'donation.education.manage',
                ],
                [
                    'key' => 'donation.share-template',
                    'label' => 'Template Share WA',
                    'route' => 'admin.donasi-pendidikan.share-template',
                    'route_active' => 'admin.donasi-pendidikan.share-template',
                    'icon' => 'chat-dots',
                    'roles' => ['superadmin', 'admin', 'staf_keuangan'],
                    'permission' => 'donation.education.manage',
                ],
            ],
        ],
        [
            'label' => 'ORANG TUA ASUH',
            'items' => [
                [
                    'key' => 'foster.parents',
                    'label' => 'Pengajuan OTA',
                    'route' => 'admin.orang-tua-asuh.index',
                    'route_active' => 'admin.orang-tua-asuh.*',
                    'icon' => 'users',
                    'roles' => ['superadmin', 'admin', 'staf_kesiswaan'],
                    'permission' => 'foster.parents.view',
                ],
            ],
        ],
        [
            'label' => 'WAKAF',
            'items' => [
                [
                    'key' => 'wakaf.receipt',
                    'label' => 'Buat Bukti Penerimaan',
                    'route' => 'admin.wakaf.transactions.create-receipt',
                    'route_active' => 'admin.wakaf.transactions.create-receipt',
                    'icon' => 'plus',
                    'roles' => ['superadmin', 'admin', 'staf_keuangan'],
                    'permission' => 'wakaf.transactions.manage',
                ],
                [
                    'key' => 'wakaf.settings',
                    'label' => 'Pengaturan Wakaf',
                    'route' => 'admin.wakaf.settings.edit',
                    'route_active' => 'admin.wakaf.settings.*',
                    'icon' => 'gear',
                    'roles' => ['superadmin', 'admin', 'staf_keuangan'],
                    'permission' => 'wakaf.settings.manage',
                ],
                [
                    'key' => 'wakaf.transactions',
                    'label' => 'Wakaf Masuk',
                    'route' => 'admin.wakaf.transactions.index',
                    'route_active' => 'admin.wakaf.transactions.index',
                    'icon' => 'checkmark',
                    'roles' => ['superadmin', 'admin', 'staf_keuangan', 'kepala_sekolah'],
                    'permission' => 'wakaf.transactions.view',
                ],
            ],
        ],
        [
            'label' => 'SARPRAS',
            'items' => [
                [
                    'key' => 'sarpras.dashboard',
                    'label' => 'Dashboard Sarpras',
                    'route' => 'admin.sarpras.dashboard',
                    'route_active' => 'admin.sarpras.dashboard',
                    'icon' => 'home',
                    'roles' => ['superadmin', 'admin', 'staf_sarpras', 'kepala_sekolah'],
                    'permission' => 'sarpras.dashboard.view',
                ],
                [
                    'key' => 'sarpras.assets',
                    'label' => 'Data Aset',
                    'route' => 'admin.sarpras.assets.index',
                    'route_active' => 'admin.sarpras.assets.*',
                    'icon' => 'box',
                    'roles' => ['superadmin', 'admin', 'staf_sarpras'],
                    'permission' => 'sarpras.assets.manage',
                ],
                [
                    'key' => 'sarpras.rooms',
                    'label' => 'Data Ruangan',
                    'route' => 'admin.sarpras.rooms.index',
                    'route_active' => 'admin.sarpras.rooms.*',
                    'icon' => 'folder',
                    'roles' => ['superadmin', 'admin', 'staf_sarpras'],
                    'permission' => 'sarpras.rooms.manage',
                ],
                [
                    'key' => 'sarpras.needs',
                    'label' => 'Kebutuhan Sarpras',
                    'route' => 'admin.sarpras.needs.index',
                    'route_active' => 'admin.sarpras.needs.*',
                    'icon' => 'plus-circle',
                    'roles' => ['superadmin', 'admin', 'staf_sarpras'],
                    'permission' => 'sarpras.needs.manage',
                ],
                [
                    'key' => 'sarpras.report',
                    'label' => 'Laporan Sarpras',
                    'route' => 'admin.sarpras.laporan',
                    'route_active' => 'admin.sarpras.laporan',
                    'icon' => 'clipboard',
                    'roles' => ['superadmin', 'admin', 'staf_sarpras', 'kepala_sekolah'],
                    'permission' => 'sarpras.report.view',
                ],
                [
                    'key' => 'sarpras.maintenances',
                    'label' => 'Perbaikan',
                    'route' => 'admin.sarpras.maintenances.index',
                    'route_active' => 'admin.sarpras.maintenances.*',
                    'icon' => 'gear',
                    'roles' => ['superadmin', 'admin', 'staf_sarpras'],
                    'permission' => 'sarpras.maintenances.manage',
                ],
                [
                    'key' => 'sarpras.procurements',
                    'label' => 'Pengadaan Barang',
                    'route' => 'admin.sarpras.procurements.index',
                    'route_active' => 'admin.sarpras.procurements.*',
                    'icon' => 'shopping-bag',
                    'roles' => ['superadmin', 'admin', 'staf_sarpras'],
                    'permission' => 'sarpras.procurements.manage',
                ],
            ],
        ],
        [
            'label' => 'WEBSITE',
            'items' => [
                [
                    'key' => 'website.media',
                    'label' => 'Galeri Sekolah',
                    'route' => 'admin.website.media.index',
                    'route_active' => 'admin.website.media.*',
                    'icon' => 'image',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.media.manage',
                ],
                [
                    'key' => 'website.categories',
                    'label' => 'Kategori Galeri',
                    'route' => 'admin.website.categories.index',
                    'route_active' => 'admin.website.categories.*',
                    'icon' => 'tag',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.categories.manage',
                ],
                [
                    'key' => 'website.boarding',
                    'label' => 'Konten Boarding',
                    'route' => 'admin.website.boarding.index',
                    'route_active' => 'admin.website.boarding.*',
                    'icon' => 'home',
                    'indent' => true,
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.boarding.manage',
                ],
                [
                    'key' => 'website.pages',
                    'label' => 'Konten Halaman',
                    'route' => 'admin.website.pages.index',
                    'route_active' => 'admin.website.pages.*',
                    'icon' => 'list',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.pages.manage',
                ],
                [
                    'key' => 'website.menus',
                    'label' => 'Menu Navigasi',
                    'route' => 'admin.website.menus.index',
                    'route_active' => 'admin.website.menus.*',
                    'icon' => 'menu-bars',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.menus.manage',
                ],
                [
                    'key' => 'website.values',
                    'label' => 'Nilai Utama',
                    'route' => 'admin.website.values.index',
                    'route_active' => 'admin.website.values.*',
                    'icon' => 'star',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.values.manage',
                ],
                [
                    'key' => 'website.settings',
                    'label' => 'Pengaturan Website',
                    'route' => 'admin.website.settings.edit',
                    'route_active' => 'admin.website.settings.edit',
                    'icon' => 'gear',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.settings.manage',
                ],
                [
                    'key' => 'website.figures',
                    'label' => 'Tokoh & Pembina',
                    'route' => 'admin.website.figures.index',
                    'route_active' => 'admin.website.figures.*',
                    'icon' => 'person',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.figures.manage',
                ],
            ],
        ],
        [
            'label' => 'AKADEMIK',
            'items' => [
                [
                    'key' => 'academic.schedule',
                    'label' => 'Jadwal Pelajaran',
                    'route' => 'admin.akademik.jadwal-pelajaran.index',
                    'route_active' => 'admin.akademik.jadwal-pelajaran.*',
                    'icon' => 'clipboard',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah', 'guru'],
                    'permission' => 'academic.schedule.view',
                ],
                [
                    'key' => 'academic.hours',
                    'label' => 'Jam Pelajaran',
                    'route' => 'admin.akademik.jam-pelajaran.index',
                    'route_active' => 'admin.akademik.jam-pelajaran.*',
                    'icon' => 'clock',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah', 'guru'],
                    'permission' => 'academic.hours.view',
                ],
                [
                    'key' => 'academic.calendar',
                    'label' => 'Kalender Pendidikan',
                    'route' => 'admin.akademik.kalender.index',
                    'route_active' => 'admin.akademik.kalender.*',
                    'icon' => 'calendar',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah', 'guru'],
                    'permission' => 'academic.calendar.view',
                ],
                [
                    'key' => 'academic.classes',
                    'label' => 'Kelas / Rombel',
                    'route' => 'admin.akademik.kelas.index',
                    'route_active' => 'admin.akademik.kelas.*',
                    'icon' => 'building',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah', 'guru'],
                    'permission' => 'academic.classes.view',
                ],
                [
                    'key' => 'academic.subjects',
                    'label' => 'Mata Pelajaran',
                    'route' => 'admin.website.subjects.index',
                    'route_active' => 'admin.website.subjects.*',
                    'icon' => 'book',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.subjects.manage',
                ],
                [
                    'key' => 'academic.teachers',
                    'label' => 'Profil Guru',
                    'route' => 'admin.website.teachers.index',
                    'route_active' => 'admin.website.teachers.*',
                    'icon' => 'person',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.teachers.manage',
                ],
                [
                    'key' => 'academic.organization',
                    'label' => 'Struktur Organisasi',
                    'route' => 'admin.organization-structures.index',
                    'route_active' => 'admin.organization-structures.*',
                    'icon' => 'grid',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha'],
                    'permission' => 'website.organization.manage',
                ],
                [
                    'key' => 'academic.years',
                    'label' => 'Tahun Pelajaran',
                    'route' => 'admin.akademik.tahun-pelajaran.index',
                    'route_active' => 'admin.akademik.tahun-pelajaran.*',
                    'icon' => 'list-details',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah'],
                    'permission' => 'academic.years.view',
                ],
            ],
        ],
        [
            'label' => 'SISTEM',
            'items' => [
                [
                    'key' => 'system.faq',
                    'label' => 'FAQ AI',
                    'route' => 'admin.ai-faqs.index',
                    'route_active' => 'admin.ai-faqs.*',
                    'icon' => 'lightbulb',
                    'roles' => ['superadmin', 'admin', 'staf_tata_usaha', 'guru'],
                    'permission' => 'website.faq-ai.view',
                ],
                [
                    'key' => 'system.users',
                    'label' => 'Kelola User',
                    'route' => 'admin.users.index',
                    'route_active' => 'admin.users.*',
                    'icon' => 'users',
                    'roles' => ['superadmin'],
                    'permission' => 'system.users.manage',
                ],
                [
                    'key' => 'system.menu-access',
                    'label' => 'Pengaturan Menu',
                    'route' => 'admin.menu-access.index',
                    'route_active' => 'admin.menu-access.*',
                    'icon' => 'eye',
                    'roles' => ['superadmin'],
                    'permission' => 'system.menu.manage',
                ],
                [
                    'key' => 'system.roles',
                    'label' => 'Pengaturan Role',
                    'route' => 'admin.roles.index',
                    'route_active' => 'admin.roles.*',
                    'icon' => 'shield',
                    'roles' => ['superadmin'],
                    'permission' => 'system.roles.manage',
                ],
            ],
        ],
    ],

    'account' => [
        'label' => 'AKUN',
        'items' => [
            [
                'key' => 'account.profile',
                'label' => 'Profil',
                'route' => 'profile.edit',
                'route_active' => 'profile.*',
                'icon' => 'person',
                'roles' => [],
            ],
        ],
    ],
];
