<?php

return [
    // ========================================================================
    // SYSTEM PERMISSIONS — superadmin-only, is_system=true
    // ========================================================================
    [
        'name'          => 'system.users.manage',
        'module'        => 'system',
        'action'        => 'manage',
        'display_name'  => 'Kelola Pengguna',
        'description'   => 'Membuat, mengedit, menonaktifkan akun pengguna',
        'group_name'    => 'SISTEM',
        'routes'        => [
            'admin.users.index',
            'admin.users.create',
            'admin.users.store',
            'admin.users.edit',
            'admin.users.update',
        ],
        'default_roles' => [],
        'menu_key'      => 'system.users',
        'is_system'     => true,
        'sort_order'    => 1,
    ],
    [
        'name'          => 'system.roles.manage',
        'module'        => 'system',
        'action'        => 'manage',
        'display_name'  => 'Kelola Role',
        'description'   => 'Membuat, mengedit, menonaktifkan role pengguna',
        'group_name'    => 'SISTEM',
        'routes'        => [
            'admin.roles.index',
            'admin.roles.store',
            'admin.roles.update',
            'admin.roles.toggle-active',
            'admin.roles.destroy',
        ],
        'default_roles' => [],
        'menu_key'      => 'system.roles',
        'is_system'     => true,
        'sort_order'    => 2,
    ],
    [
        'name'          => 'system.permissions.manage',
        'module'        => 'system',
        'action'        => 'manage',
        'display_name'  => 'Kelola Hak Akses',
        'description'   => 'RESERVED — Mengatur assignment permission setiap role',
        'group_name'    => 'SISTEM',
        'routes'        => [],
        'default_roles' => [],
        'menu_key'      => null,
        'is_system'     => true,
        'sort_order'    => 3,
    ],
    [
        'name'          => 'system.menu.manage',
        'module'        => 'system',
        'action'        => 'manage',
        'display_name'  => 'Kelola Pengaturan Menu Sistem',
        'description'   => 'Mengatur hak akses menu melalui dashboard',
        'group_name'    => 'SISTEM',
        'routes'        => [
            'admin.menu-access.index',
            'admin.menu-access.update',
        ],
        'default_roles' => [],
        'menu_key'      => 'system.menu-access',
        'is_system'     => true,
        'sort_order'    => 4,
    ],

    // ========================================================================
    // SPMB
    // ========================================================================
    [
        'name'          => 'ppdb.dashboard.view',
        'module'        => 'ppdb',
        'action'        => 'view',
        'display_name'  => 'Lihat Dashboard SPMB',
        'description'   => 'Melihat dashboard PPDB/SPMB',
        'group_name'    => 'SPMB',
        'routes'        => ['admin.ppdb.dashboard'],
        'default_roles' => ['admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah'],
        'menu_key'      => 'ppdb.dashboard',
        'is_system'     => false,
        'sort_order'    => 10,
    ],
    [
        'name'          => 'ppdb.applications.view',
        'module'        => 'ppdb',
        'action'        => 'view',
        'display_name'  => 'Lihat Data Pendaftaran',
        'description'   => 'Melihat daftar dan detail pendaftar',
        'group_name'    => 'SPMB',
        'routes'        => [
            'admin.ppdb.applications.index',
            'admin.ppdb.applications.show',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah'],
        'menu_key'      => 'ppdb.applications',
        'is_system'     => false,
        'sort_order'    => 11,
    ],
    [
        'name'          => 'ppdb.applications.manage',
        'module'        => 'ppdb',
        'action'        => 'manage',
        'display_name'  => 'Kelola Pendaftaran',
        'description'   => 'Update status, follow-up, mark data complete, generate update link',
        'group_name'    => 'SPMB',
        'routes'        => [
            'admin.ppdb.applications.update-status',
            'admin.ppdb.applications.update-follow-up',
            'admin.ppdb.applications.mark-data-complete',
            'admin.ppdb.applications.generate-update-link',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha', 'staf_kesiswaan'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 12,
    ],
    [
        'name'          => 'ppdb.applications.export',
        'module'        => 'ppdb',
        'action'        => 'export',
        'display_name'  => 'Export Data Pendaftaran',
        'description'   => 'Export dan cetak data pendaftaran (Excel, PDF, print)',
        'group_name'    => 'SPMB',
        'routes'        => [
            'admin.ppdb.applications.export',
            'admin.ppdb.applications.export-pdf',
            'admin.ppdb.applications.print',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha', 'staf_kesiswaan'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 13,
    ],
    [
        'name'          => 'ppdb.applications.delete',
        'module'        => 'ppdb',
        'action'        => 'delete',
        'display_name'  => 'Hapus Data Pendaftaran',
        'description'   => 'Menghapus data pendaftar',
        'group_name'    => 'SPMB',
        'routes'        => ['admin.ppdb.applications.destroy'],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 14,
    ],
    [
        'name'          => 'ppdb.applications.download',
        'module'        => 'ppdb',
        'action'        => 'download',
        'display_name'  => 'Download Persyaratan',
        'description'   => 'Mengunduh file persyaratan pendaftar',
        'group_name'    => 'SPMB',
        'routes'        => ['admin.ppdb.applications.requirements.download'],
        'default_roles' => ['admin', 'staf_tata_usaha', 'staf_kesiswaan'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 15,
    ],
    [
        'name'          => 'ppdb.settings.manage',
        'module'        => 'ppdb',
        'action'        => 'manage',
        'display_name'  => 'Kelola Pengaturan SPMB',
        'description'   => 'Mengubah pengaturan PPDB/SPMB',
        'group_name'    => 'SPMB',
        'routes'        => [
            'admin.ppdb.settings.edit',
            'admin.ppdb.settings.update',
        ],
        'default_roles' => ['admin'],
        'menu_key'      => 'ppdb.settings',
        'is_system'     => false,
        'sort_order'    => 16,
    ],

    // ========================================================================
    // WEBSITE
    // ========================================================================
    [
        'name'          => 'website.settings.manage',
        'module'        => 'website',
        'action'        => 'manage',
        'display_name'  => 'Kelola Pengaturan Website',
        'description'   => 'Mengubah nama sekolah, kontak, logo, hero images',
        'group_name'    => 'WEBSITE',
        'routes'        => [
            'admin.website.settings.edit',
            'admin.website.settings.update',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'website.settings',
        'is_system'     => false,
        'sort_order'    => 20,
    ],
    [
        'name'          => 'website.settings.token',
        'module'        => 'website',
        'action'        => 'token',
        'display_name'  => 'Generate Token Dashboard Publik',
        'description'   => 'Membuat token untuk dashboard publik',
        'group_name'    => 'WEBSITE',
        'routes'        => ['admin.website.settings.public-dashboard-token.generate'],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 21,
    ],
    [
        'name'          => 'website.boarding.manage',
        'module'        => 'website',
        'action'        => 'manage',
        'display_name'  => 'Kelola Konten Boarding',
        'description'   => 'Mengelola halaman boarding school',
        'group_name'    => 'WEBSITE',
        'routes'        => [
            'admin.website.boarding.index',
            'admin.website.boarding.settings.update',
            'admin.website.boarding.cards.store',
            'admin.website.boarding.cards.update',
            'admin.website.boarding.cards.destroy',
            'admin.website.boarding.schedules.store',
            'admin.website.boarding.schedules.update',
            'admin.website.boarding.schedules.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'website.boarding',
        'is_system'     => false,
        'sort_order'    => 22,
    ],
    [
        'name'          => 'website.media.manage',
        'module'        => 'website',
        'action'        => 'manage',
        'display_name'  => 'Kelola Media dan Galeri',
        'description'   => 'Upload, toggle, hapus gambar galeri, hero, dan media',
        'group_name'    => 'WEBSITE',
        'routes'        => [
            'admin.website.media.index',
            'admin.website.media.store',
            'admin.website.media.toggle',
            'admin.website.media.destroy',
            'admin.website.hero-images.store',
            'admin.website.hero-images.toggle',
            'admin.website.hero-images.destroy',
            'admin.website.gallery-images.store',
            'admin.website.gallery-images.toggle',
            'admin.website.gallery-images.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'website.media',
        'is_system'     => false,
        'sort_order'    => 23,
    ],
    [
        'name'          => 'website.categories.manage',
        'module'        => 'website',
        'action'        => 'manage',
        'display_name'  => 'Kelola Kategori Galeri',
        'description'   => 'CRUD kategori galeri',
        'group_name'    => 'WEBSITE',
        'routes'        => [
            'admin.website.categories.index',
            'admin.website.categories.create',
            'admin.website.categories.store',
            'admin.website.categories.edit',
            'admin.website.categories.update',
            'admin.website.categories.toggle',
            'admin.website.categories.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'website.categories',
        'is_system'     => false,
        'sort_order'    => 24,
    ],
    [
        'name'          => 'website.figures.manage',
        'module'        => 'website',
        'action'        => 'manage',
        'display_name'  => 'Kelola Tokoh dan Pembina',
        'description'   => 'CRUD tokoh dan pembina sekolah',
        'group_name'    => 'WEBSITE',
        'routes'        => [
            'admin.website.figures.index',
            'admin.website.figures.create',
            'admin.website.figures.store',
            'admin.website.figures.edit',
            'admin.website.figures.update',
            'admin.website.figures.toggle',
            'admin.website.figures.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'website.figures',
        'is_system'     => false,
        'sort_order'    => 25,
    ],
    [
        'name'          => 'website.pages.manage',
        'module'        => 'website',
        'action'        => 'manage',
        'display_name'  => 'Kelola Konten Halaman',
        'description'   => 'Mengedit konten halaman website',
        'group_name'    => 'WEBSITE',
        'routes'        => [
            'admin.website.pages.index',
            'admin.website.pages.edit',
            'admin.website.pages.update',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'website.pages',
        'is_system'     => false,
        'sort_order'    => 26,
    ],
    [
        'name'          => 'website.menus.manage',
        'module'        => 'website',
        'action'        => 'manage',
        'display_name'  => 'Kelola Menu Navigasi Website',
        'description'   => 'Mengatur menu navigasi website',
        'group_name'    => 'WEBSITE',
        'routes'        => [
            'admin.website.menus.index',
            'admin.website.menus.edit',
            'admin.website.menus.update',
            'admin.website.menus.toggle',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'website.menus',
        'is_system'     => false,
        'sort_order'    => 27,
    ],
    [
        'name'          => 'website.organization.manage',
        'module'        => 'website',
        'action'        => 'manage',
        'display_name'  => 'Kelola Struktur Organisasi',
        'description'   => 'CRUD struktur organisasi dan halaman',
        'group_name'    => 'WEBSITE',
        'routes'        => [
            'admin.organization-structures.index',
            'admin.organization-structures.create',
            'admin.organization-structures.store',
            'admin.organization-structures.edit',
            'admin.organization-structures.update',
            'admin.organization-structures.destroy',
            'admin.organization-structures.page.update',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'academic.organization',
        'is_system'     => false,
        'sort_order'    => 27,
    ],
    [
        'name'          => 'website.values.manage',
        'module'        => 'website',
        'action'        => 'manage',
        'display_name'  => 'Kelola Nilai Utama',
        'description'   => 'CRUD nilai utama sekolah',
        'group_name'    => 'WEBSITE',
        'routes'        => [
            'admin.website.values.index',
            'admin.website.values.create',
            'admin.website.values.store',
            'admin.website.values.edit',
            'admin.website.values.update',
            'admin.website.values.toggle',
            'admin.website.values.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'website.values',
        'is_system'     => false,
        'sort_order'    => 28,
    ],

    // ========================================================================
    // WEBSITE – FAQ
    // ========================================================================
    [
        'name'          => 'website.faq.view',
        'module'        => 'website',
        'action'        => 'view',
        'display_name'  => 'Lihat FAQ',
        'description'   => 'Melihat daftar FAQ',
        'group_name'    => 'WEBSITE',
        'routes'        => ['admin.website.faq.index'],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'system.faq',
        'is_system'     => false,
        'sort_order'    => 29,
    ],
    [
        'name'          => 'website.faq.manage',
        'module'        => 'website',
        'action'        => 'manage',
        'display_name'  => 'Kelola FAQ',
        'description'   => 'CRUD FAQ',
        'group_name'    => 'WEBSITE',
        'routes'        => [
            'admin.website.faq.create',
            'admin.website.faq.store',
            'admin.website.faq.edit',
            'admin.website.faq.update',
            'admin.website.faq.toggle',
            'admin.website.faq.destroy',
            'admin.ai-faqs.create',
            'admin.ai-faqs.store',
            'admin.ai-faqs.edit',
            'admin.ai-faqs.update',
            'admin.ai-faqs.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 30,
    ],
    [
        'name'          => 'website.faq-ai.view',
        'module'        => 'website',
        'action'        => 'view',
        'display_name'  => 'Lihat AI FAQ',
        'description'   => 'Melihat daftar AI FAQ',
        'group_name'    => 'WEBSITE',
        'routes'        => ['admin.ai-faqs.index'],
        'default_roles' => ['admin', 'staf_tata_usaha', 'guru'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 31,
    ],

    // ========================================================================
    // AKADEMIK – PROFIL GURU
    // ========================================================================
    [
        'name'          => 'website.teachers.manage',
        'module'        => 'academic',
        'action'        => 'manage',
        'display_name'  => 'Kelola Profil Guru',
        'description'   => 'CRUD profil guru, generate dan reset token edit publik',
        'group_name'    => 'AKADEMIK',
        'routes'        => [
            'admin.website.teachers.index',
            'admin.website.teachers.create',
            'admin.website.teachers.store',
            'admin.website.teachers.edit',
            'admin.website.teachers.update',
            'admin.website.teachers.toggle',
            'admin.website.teachers.destroy',
            'admin.website.teachers.generate-token',
            'admin.website.teachers.reset-token',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'academic.teachers',
        'is_system'     => false,
        'sort_order'    => 31,
    ],

    // ========================================================================
    // AKADEMIK – MATA PELAJARAN
    // ========================================================================
    [
        'name'          => 'website.subjects.manage',
        'module'        => 'academic',
        'action'        => 'manage',
        'display_name'  => 'Kelola Mata Pelajaran',
        'description'   => 'CRUD mata pelajaran dan relasi guru',
        'group_name'    => 'AKADEMIK',
        'routes'        => [
            'admin.website.subjects.index',
            'admin.website.subjects.create',
            'admin.website.subjects.store',
            'admin.website.subjects.edit',
            'admin.website.subjects.update',
            'admin.website.subjects.toggle',
            'admin.website.subjects.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'academic.subjects',
        'is_system'     => false,
        'sort_order'    => 32,
    ],

    // ========================================================================
    // AKADEMIK – KALENDER PENDIDIKAN
    // ========================================================================
    [
        'name'          => 'academic.calendar.view',
        'module'        => 'academic',
        'action'        => 'view',
        'display_name'  => 'Lihat Kalender Pendidikan',
        'description'   => 'Melihat kalender akademik',
        'group_name'    => 'AKADEMIK',
        'routes'        => ['admin.akademik.kalender.index'],
        'default_roles' => ['admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah', 'guru'],
        'menu_key'      => 'academic.calendar',
        'is_system'     => false,
        'sort_order'    => 33,
    ],
    [
        'name'          => 'academic.calendar.manage',
        'module'        => 'academic',
        'action'        => 'manage',
        'display_name'  => 'Kelola Kalender Pendidikan',
        'description'   => 'CRUD event kalender akademik',
        'group_name'    => 'AKADEMIK',
        'routes'        => [
            'admin.akademik.kalender.create',
            'admin.akademik.kalender.store',
            'admin.akademik.kalender.edit',
            'admin.akademik.kalender.update',
            'admin.akademik.kalender.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 34,
    ],

    // ========================================================================
    // AKADEMIK – JADWAL PELAJARAN
    // ========================================================================
    [
        'name'          => 'academic.schedule.view',
        'module'        => 'academic',
        'action'        => 'view',
        'display_name'  => 'Lihat Jadwal Pelajaran',
        'description'   => 'Melihat jadwal pelajaran',
        'group_name'    => 'AKADEMIK',
        'routes'        => ['admin.akademik.jadwal-pelajaran.index'],
        'default_roles' => ['admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah', 'guru'],
        'menu_key'      => 'academic.schedule',
        'is_system'     => false,
        'sort_order'    => 35,
    ],
    [
        'name'          => 'academic.schedule.manage',
        'module'        => 'academic',
        'action'        => 'manage',
        'display_name'  => 'Kelola Jadwal Pelajaran',
        'description'   => 'CRUD jadwal pelajaran',
        'group_name'    => 'AKADEMIK',
        'routes'        => [
            'admin.akademik.jadwal-pelajaran.create',
            'admin.akademik.jadwal-pelajaran.store',
            'admin.akademik.jadwal-pelajaran.edit',
            'admin.akademik.jadwal-pelajaran.update',
            'admin.akademik.jadwal-pelajaran.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 36,
    ],

    // ========================================================================
    // AKADEMIK – TAHUN PELAJARAN
    // ========================================================================
    [
        'name'          => 'academic.years.view',
        'module'        => 'academic',
        'action'        => 'view',
        'display_name'  => 'Lihat Tahun Pelajaran',
        'description'   => 'Melihat daftar tahun pelajaran',
        'group_name'    => 'AKADEMIK',
        'routes'        => ['admin.akademik.tahun-pelajaran.index'],
        'default_roles' => ['admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah'],
        'menu_key'      => 'academic.years',
        'is_system'     => false,
        'sort_order'    => 37,
    ],
    [
        'name'          => 'academic.years.manage',
        'module'        => 'academic',
        'action'        => 'manage',
        'display_name'  => 'Kelola Tahun Pelajaran',
        'description'   => 'CRUD dan set tahun pelajaran aktif',
        'group_name'    => 'AKADEMIK',
        'routes'        => [
            'admin.akademik.tahun-pelajaran.create',
            'admin.akademik.tahun-pelajaran.store',
            'admin.akademik.tahun-pelajaran.edit',
            'admin.akademik.tahun-pelajaran.update',
            'admin.akademik.tahun-pelajaran.set-current',
            'admin.akademik.tahun-pelajaran.destroy',
        ],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 38,
    ],

    // ========================================================================
    // AKADEMIK – KELAS / ROMBEL
    // ========================================================================
    [
        'name'          => 'academic.classes.view',
        'module'        => 'academic',
        'action'        => 'view',
        'display_name'  => 'Lihat Kelas/Rombel',
        'description'   => 'Melihat daftar kelas dan rombongan belajar',
        'group_name'    => 'AKADEMIK',
        'routes'        => ['admin.akademik.kelas.index'],
        'default_roles' => ['admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah', 'guru'],
        'menu_key'      => 'academic.classes',
        'is_system'     => false,
        'sort_order'    => 39,
    ],
    [
        'name'          => 'academic.classes.manage',
        'module'        => 'academic',
        'action'        => 'manage',
        'display_name'  => 'Kelola Kelas/Rombel',
        'description'   => 'CRUD dan toggle kelas',
        'group_name'    => 'AKADEMIK',
        'routes'        => [
            'admin.akademik.kelas.create',
            'admin.akademik.kelas.store',
            'admin.akademik.kelas.edit',
            'admin.akademik.kelas.update',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 40,
    ],
    [
        'name'          => 'academic.classes.delete',
        'module'        => 'academic',
        'action'        => 'delete',
        'display_name'  => 'Hapus/Toggle Kelas',
        'description'   => 'Menghapus dan toggle status kelas',
        'group_name'    => 'AKADEMIK',
        'routes'        => [
            'admin.akademik.kelas.toggle',
            'admin.akademik.kelas.destroy',
        ],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 41,
    ],

    // ========================================================================
    // AKADEMIK – JAM PELAJARAN
    // ========================================================================
    [
        'name'          => 'academic.hours.view',
        'module'        => 'academic',
        'action'        => 'view',
        'display_name'  => 'Lihat Jam Pelajaran',
        'description'   => 'Melihat pengaturan jam pelajaran',
        'group_name'    => 'AKADEMIK',
        'routes'        => ['admin.akademik.jam-pelajaran.index'],
        'default_roles' => ['admin', 'staf_tata_usaha', 'staf_kesiswaan', 'kepala_sekolah', 'guru'],
        'menu_key'      => 'academic.hours',
        'is_system'     => false,
        'sort_order'    => 42,
    ],
    [
        'name'          => 'academic.hours.manage',
        'module'        => 'academic',
        'action'        => 'manage',
        'display_name'  => 'Kelola Jam Pelajaran',
        'description'   => 'CRUD jam pelajaran',
        'group_name'    => 'AKADEMIK',
        'routes'        => [
            'admin.akademik.jam-pelajaran.create',
            'admin.akademik.jam-pelajaran.store',
            'admin.akademik.jam-pelajaran.edit',
            'admin.akademik.jam-pelajaran.update',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 43,
    ],
    [
        'name'          => 'academic.hours.delete',
        'module'        => 'academic',
        'action'        => 'delete',
        'display_name'  => 'Hapus/Toggle Jam Pelajaran',
        'description'   => 'Menghapus dan toggle status jam pelajaran',
        'group_name'    => 'AKADEMIK',
        'routes'        => [
            'admin.akademik.jam-pelajaran.toggle',
            'admin.akademik.jam-pelajaran.destroy',
        ],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 44,
    ],

    // ========================================================================
    // KEUANGAN
    // ========================================================================
    [
        'name'          => 'finance.dashboard.view',
        'module'        => 'finance',
        'action'        => 'view',
        'display_name'  => 'Lihat Dashboard Keuangan',
        'description'   => 'Melihat dashboard keuangan',
        'group_name'    => 'KEUANGAN',
        'routes'        => ['admin.finance.dashboard'],
        'default_roles' => ['admin', 'staf_keuangan', 'kepala_sekolah'],
        'menu_key'      => 'finance.dashboard',
        'is_system'     => false,
        'sort_order'    => 50,
    ],
    [
        'name'          => 'finance.report.view',
        'module'        => 'finance',
        'action'        => 'view',
        'display_name'  => 'Lihat Laporan Keuangan',
        'description'   => 'Melihat laporan keuangan',
        'group_name'    => 'KEUANGAN',
        'routes'        => ['admin.finance.report'],
        'default_roles' => ['admin', 'staf_keuangan', 'kepala_sekolah'],
        'menu_key'      => 'finance.report',
        'is_system'     => false,
        'sort_order'    => 51,
    ],
    [
        'name'          => 'finance.transactions.manage',
        'module'        => 'finance',
        'action'        => 'manage',
        'display_name'  => 'Kelola Transaksi Keuangan',
        'description'   => 'CRUD pemasukan dan pengeluaran',
        'group_name'    => 'KEUANGAN',
        'routes'        => [
            'admin.finance.incomes.index',
            'admin.finance.incomes.create',
            'admin.finance.incomes.store',
            'admin.finance.incomes.edit',
            'admin.finance.incomes.update',
            'admin.finance.incomes.destroy',
            'admin.finance.expenses.index',
            'admin.finance.expenses.create',
            'admin.finance.expenses.store',
            'admin.finance.expenses.edit',
            'admin.finance.expenses.update',
        ],
        'default_roles' => ['admin', 'staf_keuangan'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 52,
    ],
    [
        'name'          => 'finance.transactions.delete',
        'module'        => 'finance',
        'action'        => 'delete',
        'display_name'  => 'Hapus Transaksi Keuangan',
        'description'   => 'Menghapus pemasukan dan pengeluaran',
        'group_name'    => 'KEUANGAN',
        'routes'        => [
            'admin.finance.expenses.destroy',
        ],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 53,
    ],

    // ========================================================================
    // SURAT MENYURAT
    // ========================================================================
    [
        'name'          => 'letters.outgoings.view',
        'module'        => 'letters',
        'action'        => 'view',
        'display_name'  => 'Lihat Surat Keluar',
        'description'   => 'Melihat daftar, detail, dan preview surat keluar',
        'group_name'    => 'SURAT MENYURAT',
        'routes'        => [
            'admin.letters.outgoings.index',
            'admin.letters.outgoings.show',
            'admin.letters.outgoings.preview',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha', 'kepala_sekolah'],
        'menu_key'      => 'letters.outgoings',
        'is_system'     => false,
        'sort_order'    => 60,
    ],
    [
        'name'          => 'letters.outgoings.manage',
        'module'        => 'letters',
        'action'        => 'manage',
        'display_name'  => 'Kelola Surat Keluar',
        'description'   => 'Buat, edit, issue, print, upload attachment surat keluar',
        'group_name'    => 'SURAT MENYURAT',
        'routes'        => [
            'admin.letters.outgoings.create',
            'admin.letters.outgoings.store',
            'admin.letters.outgoings.edit',
            'admin.letters.outgoings.update',
            'admin.letters.outgoings.issue.get',
            'admin.letters.outgoings.issue',
            'admin.letters.outgoings.print',
            'admin.letters.outgoings.print-all',
            'admin.letters.outgoings.print-recipient',
            'admin.letters.outgoings.update-attachment',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 61,
    ],
    [
        'name'          => 'letters.incomings.view',
        'module'        => 'letters',
        'action'        => 'view',
        'display_name'  => 'Lihat Surat Masuk',
        'description'   => 'Melihat daftar dan detail surat masuk',
        'group_name'    => 'SURAT MENYURAT',
        'routes'        => [
            'admin.letters.incomings.index',
            'admin.letters.incomings.show',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha', 'kepala_sekolah'],
        'menu_key'      => 'letters.incomings',
        'is_system'     => false,
        'sort_order'    => 62,
    ],
    [
        'name'          => 'letters.incomings.manage',
        'module'        => 'letters',
        'action'        => 'manage',
        'display_name'  => 'Kelola Surat Masuk',
        'description'   => 'CRUD surat masuk',
        'group_name'    => 'SURAT MENYURAT',
        'routes'        => [
            'admin.letters.incomings.create',
            'admin.letters.incomings.store',
            'admin.letters.incomings.edit',
            'admin.letters.incomings.update',
            'admin.letters.incomings.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 63,
    ],
    [
        'name'          => 'letters.templates.manage',
        'module'        => 'letters',
        'action'        => 'manage',
        'display_name'  => 'Kelola Template Surat',
        'description'   => 'CRUD template surat',
        'group_name'    => 'SURAT MENYURAT',
        'routes'        => [
            'admin.letters.templates.index',
            'admin.letters.templates.create',
            'admin.letters.templates.store',
            'admin.letters.templates.show',
            'admin.letters.templates.edit',
            'admin.letters.templates.update',
            'admin.letters.templates.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'letters.templates',
        'is_system'     => false,
        'sort_order'    => 64,
    ],
    [
        'name'          => 'letters.signers.manage',
        'module'        => 'letters',
        'action'        => 'manage',
        'display_name'  => 'Kelola Penandatangan',
        'description'   => 'CRUD penandatangan surat',
        'group_name'    => 'SURAT MENYURAT',
        'routes'        => [
            'admin.letters.signers.index',
            'admin.letters.signers.store',
            'admin.letters.signers.edit',
            'admin.letters.signers.update',
            'admin.letters.signers.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'letters.signers',
        'is_system'     => false,
        'sort_order'    => 65,
    ],
    [
        'name'          => 'letters.types.manage',
        'module'        => 'letters',
        'action'        => 'manage',
        'display_name'  => 'Kelola Jenis Surat',
        'description'   => 'CRUD jenis surat',
        'group_name'    => 'SURAT MENYURAT',
        'routes'        => [
            'admin.letters.types.index',
            'admin.letters.types.store',
            'admin.letters.types.edit',
            'admin.letters.types.update',
            'admin.letters.types.destroy',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'letters.types',
        'is_system'     => false,
        'sort_order'    => 66,
    ],
    [
        'name'          => 'letters.settings.manage',
        'module'        => 'letters',
        'action'        => 'manage',
        'display_name'  => 'Kelola Pengaturan Surat',
        'description'   => 'Mengubah pengaturan surat menyurat',
        'group_name'    => 'SURAT MENYURAT',
        'routes'        => [
            'admin.letters.settings.edit',
            'admin.letters.settings.update',
        ],
        'default_roles' => ['admin', 'staf_tata_usaha'],
        'menu_key'      => 'letters.settings',
        'is_system'     => false,
        'sort_order'    => 67,
    ],

    // ========================================================================
    // DONASI
    // ========================================================================
    [
        'name'          => 'donation.education.manage',
        'module'        => 'donation',
        'action'        => 'manage',
        'display_name'  => 'Kelola Donasi Pendidikan',
        'description'   => 'Mengubah pengaturan donasi pendidikan dan template share',
        'group_name'    => 'DONASI',
        'routes'        => [
            'admin.website.donasi-pendidikan.edit',
            'admin.website.donasi-pendidikan.update',
            'admin.donasi-pendidikan.share-template',
            'admin.donasi-pendidikan.share-template.update',
        ],
        'default_roles' => ['admin', 'staf_keuangan'],
        'menu_key'      => 'donation.education',
        'is_system'     => false,
        'sort_order'    => 70,
    ],
    [
        'name'          => 'donation.transactions.view',
        'module'        => 'donation',
        'action'        => 'view',
        'display_name'  => 'Lihat Transaksi Donasi',
        'description'   => 'Melihat daftar dan detail donasi masuk',
        'group_name'    => 'DONASI',
        'routes'        => [
            'admin.donasi-transactions.index',
            'admin.donasi-transactions.show',
        ],
        'default_roles' => ['admin', 'staf_keuangan', 'kepala_sekolah', 'staf_tata_usaha'],
        'menu_key'      => 'donation.transactions',
        'is_system'     => false,
        'sort_order'    => 71,
    ],
    [
        'name'          => 'donation.transactions.manage',
        'module'        => 'donation',
        'action'        => 'manage',
        'display_name'  => 'Kelola Transaksi Donasi',
        'description'   => 'Buat bukti penerimaan, mark paid/cancelled',
        'group_name'    => 'DONASI',
        'routes'        => [
            'admin.donasi-transactions.create-receipt',
            'admin.donasi-transactions.parse-receipt',
            'admin.donasi-transactions.store-receipt',
            'admin.donasi-transactions.mark-paid',
            'admin.donasi-transactions.mark-cancelled',
            'admin.donasi-transactions.destroy',
            'admin.donasi-transactions.payment-method',
            'admin.donasi-transactions.edit',
            'admin.donasi-transactions.update',
          ],
        'default_roles' => ['admin', 'staf_keuangan', 'staf_tata_usaha'],
        'menu_key'      => 'donation.receipt',
        'is_system'     => false,
        'sort_order'    => 72,
    ],
    [
        'name'          => 'donation.infaq.manage',
        'module'        => 'donation',
        'action'        => 'manage',
        'display_name'  => 'Kelola Infaq Barang',
        'description'   => 'CRUD infaq barang dan commitment WhatsApp',
        'group_name'    => 'DONASI',
        'routes'        => [
            'admin.infaq-barang.index',
            'admin.infaq-barang.create',
            'admin.infaq-barang.store',
            'admin.infaq-barang.show',
            'admin.infaq-barang-wa.index',
            'admin.infaq-barang-wa.create',
            'admin.infaq-barang-wa.parse',
            'admin.infaq-barang-wa.store',
            'admin.infaq-barang-wa.show',
            'admin.infaq-barang-wa.update-status',
        ],
        'default_roles' => ['admin', 'staf_keuangan'],
        'menu_key'      => 'donation.infaq-wa',
        'is_system'     => false,
        'sort_order'    => 73,
    ],
    [
        'name'          => 'donation.outflows.view',
        'module'        => 'donation',
        'action'        => 'view',
        'display_name'  => 'Lihat Donasi Keluar',
        'description'   => 'Melihat daftar dan detail penyerahan dana donasi ke Keuangan',
        'group_name'    => 'DONASI',
        'routes'        => [
            'admin.donation-outflows.index',
            'admin.donation-outflows.show',
            'admin.donation-outflows.destroy',
        ],
        'default_roles' => ['admin', 'staf_keuangan'],
        'menu_key'      => 'donation.outflows',
        'is_system'     => false,
        'sort_order'    => 74,
    ],
    [
        'name'          => 'donation.outflows.create',
        'module'        => 'donation',
        'action'        => 'create',
        'display_name'  => 'Buat Donasi Keluar',
        'description'   => 'Membuat penyerahan dana donasi ke Keuangan',
        'group_name'    => 'DONASI',
          'routes'        => [
            'admin.donation-outflows.create',
            'admin.donation-outflows.store',
            'admin.donation-outflows.edit',
            'admin.donation-outflows.update',
          ],
          'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 75,
    ],
    [
        'name'          => 'donation.outflows.approve',
        'module'        => 'donation',
        'action'        => 'approve',
        'display_name'  => 'Setujui Donasi Keluar',
        'description'   => 'Menyetujui penyerahan dana donasi dan membuat Pemasukan Keuangan',
        'group_name'    => 'DONASI',
        'routes'        => ['admin.donation-outflows.approve'],
        'default_roles' => ['staf_keuangan'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 76,
    ],
    [
        'name'          => 'donation.outflows.reject',
        'module'        => 'donation',
        'action'        => 'reject',
        'display_name'  => 'Tolak Donasi Keluar',
        'description'   => 'Menolak penyerahan dana donasi dengan alasan',
        'group_name'    => 'DONASI',
        'routes'        => ['admin.donation-outflows.reject'],
        'default_roles' => ['staf_keuangan'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 77,
    ],
    [
        'name'          => 'donation.balance.view',
        'module'        => 'donation',
        'action'        => 'view',
        'display_name'  => 'Lihat Saldo Donasi',
        'description'   => 'Melihat saldo dana donasi (masuk, keluar, dan saldo tersedia)',
        'group_name'    => 'DONASI',
        'routes'        => ['admin.donation.dashboard'],
        'default_roles' => ['admin', 'staf_keuangan'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 78,
    ],
    [
        'name'          => 'donation.reminders.manage',
        'module'        => 'donation',
        'action'        => 'manage',
        'display_name'  => 'Kelola Pengingat Donatur',
        'description'   => 'Mengatur jadwal pengingat WhatsApp dan menandai donatur sudah diingatkan',
        'group_name'    => 'DONASI',
        'routes'        => [
            'admin.donor-reminders.index',
            'admin.donor-reminders.update',
            'admin.donor-reminders.mark-reminded',
        ],
        'default_roles' => ['admin', 'staf_keuangan'],
        'menu_key'      => 'donation.reminders',
        'is_system'     => false,
        'sort_order'    => 79,
    ],
    [
        'name'          => 'donation.transfers.view',
        'module'        => 'donation',
        'action'        => 'view',
        'display_name'  => 'Lihat Mutasi Dana',
        'description'   => 'Melihat daftar dan detail mutasi dana dari akun Donasi ke akun Keuangan',
        'group_name'    => 'DONASI',
        'routes'        => [
            'admin.donation-transfers.index',
            'admin.donation-transfers.show',
        ],
        'default_roles' => ['admin', 'staf_keuangan'],
        'menu_key'      => 'donation.transfers',
        'is_system'     => false,
        'sort_order'    => 80,
    ],
    [
        'name'          => 'donation.transfers.create',
        'module'        => 'donation',
        'action'        => 'create',
        'display_name'  => 'Buat Mutasi Dana',
        'description'   => 'Membuat mutasi dana dari akun Donasi ke akun Keuangan',
        'group_name'    => 'DONASI',
        'routes'        => [
            'admin.donation-transfers.create',
            'admin.donation-transfers.store',
        ],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 81,
    ],
    [
        'name'          => 'donation.transfers.approve',
        'module'        => 'donation',
        'action'        => 'approve',
        'display_name'  => 'Setujui Mutasi Dana',
        'description'   => 'Menyetujui mutasi dana dari akun Donasi ke akun Keuangan',
        'group_name'    => 'DONASI',
        'routes'        => ['admin.donation-transfers.approve'],
        'default_roles' => ['staf_keuangan'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 82,
    ],
    [
        'name'          => 'donation.transfers.reject',
        'module'        => 'donation',
        'action'        => 'reject',
        'display_name'  => 'Tolak Mutasi Dana',
        'description'   => 'Menolak mutasi dana dengan alasan',
        'group_name'    => 'DONASI',
        'routes'        => ['admin.donation-transfers.reject'],
        'default_roles' => ['staf_keuangan'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 83,
    ],

    // ========================================================================
    // ORANG TUA ASUH
    // ========================================================================
    [
        'name'          => 'foster.parents.view',
        'module'        => 'foster',
        'action'        => 'view',
        'display_name'  => 'Lihat Pengajuan Orang Tua Asuh',
        'description'   => 'Melihat daftar dan detail pengajuan orang tua asuh',
        'group_name'    => 'ORANG TUA ASUH',
        'routes'        => [
            'admin.orang-tua-asuh.index',
            'admin.orang-tua-asuh.show',
        ],
        'default_roles' => ['admin', 'staf_kesiswaan'],
        'menu_key'      => 'foster.parents',
        'is_system'     => false,
        'sort_order'    => 80,
    ],
    [
        'name'          => 'foster.parents.manage',
        'module'        => 'foster',
        'action'        => 'manage',
        'display_name'  => 'Kelola Pengajuan Orang Tua Asuh',
        'description'   => 'Update status pengajuan',
        'group_name'    => 'ORANG TUA ASUH',
        'routes'        => ['admin.orang-tua-asuh.update-status'],
        'default_roles' => ['admin', 'staf_kesiswaan'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 81,
    ],
    [
        'name'          => 'foster.parents.delete',
        'module'        => 'foster',
        'action'        => 'delete',
        'display_name'  => 'Hapus Pengajuan Orang Tua Asuh',
        'description'   => 'Menghapus pengajuan orang tua asuh',
        'group_name'    => 'ORANG TUA ASUH',
        'routes'        => ['admin.orang-tua-asuh.destroy'],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 82,
    ],

    // ========================================================================
    // WAKAF
    // ========================================================================
    [
        'name'          => 'wakaf.settings.manage',
        'module'        => 'wakaf',
        'action'        => 'manage',
        'display_name'  => 'Kelola Pengaturan Wakaf',
        'description'   => 'Mengubah pengaturan wakaf',
        'group_name'    => 'WAKAF',
        'routes'        => [
            'admin.wakaf.settings.edit',
            'admin.wakaf.settings.update',
        ],
        'default_roles' => ['admin', 'staf_keuangan'],
        'menu_key'      => 'wakaf.settings',
        'is_system'     => false,
        'sort_order'    => 90,
    ],
    [
        'name'          => 'wakaf.transactions.view',
        'module'        => 'wakaf',
        'action'        => 'view',
        'display_name'  => 'Lihat Transaksi Wakaf',
        'description'   => 'Melihat daftar dan detail wakaf masuk',
        'group_name'    => 'WAKAF',
        'routes'        => [
            'admin.wakaf.transactions.index',
            'admin.wakaf.transactions.show',
        ],
        'default_roles' => ['admin', 'staf_keuangan', 'kepala_sekolah'],
        'menu_key'      => 'wakaf.transactions',
        'is_system'     => false,
        'sort_order'    => 91,
    ],
    [
        'name'          => 'wakaf.transactions.manage',
        'module'        => 'wakaf',
        'action'        => 'manage',
        'display_name'  => 'Kelola Transaksi Wakaf',
        'description'   => 'Buat bukti penerimaan, mark paid/cancelled',
        'group_name'    => 'WAKAF',
        'routes'        => [
            'admin.wakaf.transactions.create-receipt',
            'admin.wakaf.transactions.parse-receipt',
            'admin.wakaf.transactions.store-receipt',
            'admin.wakaf.transactions.mark-paid',
            'admin.wakaf.transactions.mark-cancelled',
        ],
        'default_roles' => ['admin', 'staf_keuangan'],
        'menu_key'      => 'wakaf.receipt',
        'is_system'     => false,
        'sort_order'    => 92,
    ],

    // ========================================================================
    // SARPRAS
    // ========================================================================
    [
        'name'          => 'sarpras.dashboard.view',
        'module'        => 'sarpras',
        'action'        => 'view',
        'display_name'  => 'Lihat Dashboard Sarpras',
        'description'   => 'Melihat dashboard sarana prasarana',
        'group_name'    => 'SARPRAS',
        'routes'        => ['admin.sarpras.dashboard'],
        'default_roles' => ['admin', 'staf_sarpras', 'kepala_sekolah'],
        'menu_key'      => 'sarpras.dashboard',
        'is_system'     => false,
        'sort_order'    => 100,
    ],
    [
        'name'          => 'sarpras.report.view',
        'module'        => 'sarpras',
        'action'        => 'view',
        'display_name'  => 'Lihat Laporan Sarpras',
        'description'   => 'Melihat laporan sarana prasarana',
        'group_name'    => 'SARPRAS',
        'routes'        => ['admin.sarpras.laporan'],
        'default_roles' => ['admin', 'staf_sarpras', 'kepala_sekolah'],
        'menu_key'      => 'sarpras.report',
        'is_system'     => false,
        'sort_order'    => 101,
    ],
    [
        'name'          => 'sarpras.assets.manage',
        'module'        => 'sarpras',
        'action'        => 'manage',
        'display_name'  => 'Kelola Data Aset',
        'description'   => 'CRUD data aset sarpras',
        'group_name'    => 'SARPRAS',
        'routes'        => [
            'admin.sarpras.assets.index',
            'admin.sarpras.assets.create',
            'admin.sarpras.assets.store',
            'admin.sarpras.assets.show',
            'admin.sarpras.assets.edit',
            'admin.sarpras.assets.update',
        ],
        'default_roles' => ['admin', 'staf_sarpras'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 102,
    ],
    [
        'name'          => 'sarpras.assets.delete',
        'module'        => 'sarpras',
        'action'        => 'delete',
        'display_name'  => 'Hapus Data Aset',
        'description'   => 'Menghapus data aset',
        'group_name'    => 'SARPRAS',
        'routes'        => ['admin.sarpras.assets.destroy'],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 103,
    ],
    [
        'name'          => 'sarpras.rooms.manage',
        'module'        => 'sarpras',
        'action'        => 'manage',
        'display_name'  => 'Kelola Data Ruangan',
        'description'   => 'CRUD data ruangan',
        'group_name'    => 'SARPRAS',
        'routes'        => [
            'admin.sarpras.rooms.index',
            'admin.sarpras.rooms.create',
            'admin.sarpras.rooms.store',
            'admin.sarpras.rooms.edit',
            'admin.sarpras.rooms.update',
        ],
        'default_roles' => ['admin', 'staf_sarpras'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 104,
    ],
    [
        'name'          => 'sarpras.rooms.delete',
        'module'        => 'sarpras',
        'action'        => 'delete',
        'display_name'  => 'Hapus Data Ruangan',
        'description'   => 'Menghapus data ruangan',
        'group_name'    => 'SARPRAS',
        'routes'        => ['admin.sarpras.rooms.destroy'],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 105,
    ],
    [
        'name'          => 'sarpras.needs.manage',
        'module'        => 'sarpras',
        'action'        => 'manage',
        'display_name'  => 'Kelola Kebutuhan Sarpras',
        'description'   => 'CRUD kebutuhan sarpras',
        'group_name'    => 'SARPRAS',
        'routes'        => [
            'admin.sarpras.needs.index',
            'admin.sarpras.needs.create',
            'admin.sarpras.needs.store',
            'admin.sarpras.needs.edit',
            'admin.sarpras.needs.update',
        ],
        'default_roles' => ['admin', 'staf_sarpras'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 106,
    ],
    [
        'name'          => 'sarpras.needs.delete',
        'module'        => 'sarpras',
        'action'        => 'delete',
        'display_name'  => 'Hapus Kebutuhan Sarpras',
        'description'   => 'Menghapus kebutuhan sarpras',
        'group_name'    => 'SARPRAS',
        'routes'        => ['admin.sarpras.needs.destroy'],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 107,
    ],
    [
        'name'          => 'sarpras.maintenances.manage',
        'module'        => 'sarpras',
        'action'        => 'manage',
        'display_name'  => 'Kelola Perbaikan',
        'description'   => 'CRUD perbaikan sarpras',
        'group_name'    => 'SARPRAS',
        'routes'        => [
            'admin.sarpras.maintenances.index',
            'admin.sarpras.maintenances.create',
            'admin.sarpras.maintenances.store',
            'admin.sarpras.maintenances.edit',
            'admin.sarpras.maintenances.update',
        ],
        'default_roles' => ['admin', 'staf_sarpras'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 108,
    ],
    [
        'name'          => 'sarpras.maintenances.delete',
        'module'        => 'sarpras',
        'action'        => 'delete',
        'display_name'  => 'Hapus Perbaikan',
        'description'   => 'Menghapus data perbaikan',
        'group_name'    => 'SARPRAS',
        'routes'        => ['admin.sarpras.maintenances.destroy'],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 109,
    ],
    [
        'name'          => 'sarpras.procurements.manage',
        'module'        => 'sarpras',
        'action'        => 'manage',
        'display_name'  => 'Kelola Pengadaan Barang',
        'description'   => 'CRUD pengadaan barang',
        'group_name'    => 'SARPRAS',
        'routes'        => [
            'admin.sarpras.procurements.index',
            'admin.sarpras.procurements.create',
            'admin.sarpras.procurements.store',
            'admin.sarpras.procurements.edit',
            'admin.sarpras.procurements.update',
        ],
        'default_roles' => ['admin', 'staf_sarpras'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 110,
    ],
    [
        'name'          => 'sarpras.procurements.delete',
        'module'        => 'sarpras',
        'action'        => 'delete',
        'display_name'  => 'Hapus Pengadaan Barang',
        'description'   => 'Menghapus data pengadaan barang',
        'group_name'    => 'SARPRAS',
        'routes'        => ['admin.sarpras.procurements.destroy'],
        'default_roles' => ['admin'],
        'menu_key'      => null,
        'is_system'     => false,
        'sort_order'    => 111,
    ],
];
