<?php

return [
    'asset_categories' => [
        'Meubelair',
        'Elektronik',
        'Komputer & Jaringan',
        'Alat Pembelajaran',
        'Buku & Perpustakaan',
        'Peralatan Asrama',
        'Peralatan Dapur',
        'Peralatan Kebersihan',
        'Peralatan Olahraga',
        'Peralatan Ibadah',
        'Bangunan & Fasilitas',
        'Kendaraan',
        'Lainnya',
    ],

    'asset_conditions' => [
        'baik' => 'Baik',
        'rusak_ringan' => 'Rusak Ringan',
        'rusak_berat' => 'Rusak Berat',
        'hilang' => 'Hilang',
    ],

    'room_types' => [
        'Ruang Kelas',
        'Kantor',
        'Ruang Guru',
        'Ruang Kepala Sekolah',
        'Tata Usaha',
        'Asrama Ikhwan',
        'Asrama Akhwat',
        'Dapur',
        'Toilet',
        'Lab Komputer',
        'Perpustakaan',
        'Gudang',
        'Mushala',
        'Lapangan',
        'Ruang UKS',
        'Lainnya',
    ],

    'room_conditions' => [
        'baik' => 'Baik',
        'rusak_ringan' => 'Rusak Ringan',
        'rusak_berat' => 'Rusak Berat',
        'perlu_perbaikan' => 'Perlu Perbaikan',
    ],

    'need_categories' => [
        'Meubelair',
        'Elektronik',
        'Komputer & Jaringan',
        'Pembelajaran',
        'Asrama',
        'Dapur',
        'Kebersihan',
        'Olahraga',
        'Ibadah',
        'Bangunan',
        'Keamanan',
        'Lainnya',
    ],

    'need_priorities' => [
        'mendesak' => 'Mendesak',
        'penting' => 'Penting',
        'sedang' => 'Sedang',
        'rendah' => 'Rendah',
    ],

    'need_statuses' => [
        'diajukan' => 'Diajukan',
        'disetujui' => 'Disetujui',
        'proses_pengadaan' => 'Proses Pengadaan',
        'terpenuhi' => 'Terpenuhi',
        'ditunda' => 'Ditunda',
    ],

    'maintenance_statuses' => [
        'dilaporkan' => 'Dilaporkan',
        'dicek' => 'Dicek',
        'proses_perbaikan' => 'Proses Perbaikan',
        'selesai' => 'Selesai',
        'tidak_bisa_diperbaiki' => 'Tidak Bisa Diperbaiki',
    ],

    'procurement_statuses' => [
        'rencana' => 'Rencana',
        'proses' => 'Proses',
        'selesai' => 'Selesai',
        'dibatalkan' => 'Dibatalkan',
    ],

    'units' => [
        'Unit',
        'Buah',
        'Set',
        'Pasang',
        'Paket',
        'Meter',
        'Roll',
        'Dus',
        'Liter',
        'Kg',
        'Lembar',
        'Eksemplar',
        'Lainnya',
    ],

    'source_funds' => [
        'Dana Sekolah',
        'Donasi Pendidikan',
        'Wakaf',
        'Infak',
        'Bantuan Pemerintah',
        'Bantuan Yayasan',
        'Bantuan Orang Tua',
        'CSR',
        'Hibah',
        'Lainnya',
    ],

    'default_locations' => [
        'Ruang Kelas 1',
        'Ruang Kelas 2',
        'Ruang Guru',
        'Kantor',
        'Tata Usaha',
        'Asrama Ikhwan',
        'Asrama Akhwat',
        'Dapur',
        'Toilet',
        'Lab Komputer',
        'Perpustakaan',
        'Gudang',
        'Mushala',
        'Lapangan',
        'Area Depan',
        'Area Belakang',
        'Lainnya',
    ],
];
